apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-telegram-webhook
  namespace: customer1
spec:
  parentRefs:
  - name: external-http-gateway
    sectionName: https
  hostnames:
  - "ws.siriusdevops.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /telegram/webhook
    backendRefs:
    - name: http-tele-webhook 
      port: 9118
