apiVersion: v1
kind: Secret
metadata:
    name: waitlist-telegram-secret
    namespace: customer1
type: Opaque
stringData:
    bot_token: CHANGEME
    chat_id: CHANGEME
sops:
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
    encrypted_regex: ^(data|stringData)$
