apiVersion: v1
kind: Secret
metadata:
    name: waitlist-telegram-secret
    namespace: customer1
type: Opaque
stringData:
    bot_token: ENC[AES256_GCM,data:Oc0SMrjZpO0=,iv:7MUe7Ew4Hvmp83AYVhz6yyX431NckEwK2lEfuxqFqKA=,tag:MTIs8XDzxNbHll9MiEdGlw==,type:str]
    chat_id: ENC[AES256_GCM,data:TmRBJWB7gHo=,iv:DDEdFefsw4zmhLfGpO8OMI0VR1J81GBatSGnkZMKgDI=,tag:n2gJwD873wMagBFaxv2sxQ==,type:str]
    admin_api_key: ENC[AES256_GCM,data:S3VdB11Z37hxz1gIRCODkO36ZdoaifDGx1QmmCKOf8k=,iv:FvoGOdAf6Mzf+riWOx780M6zoGK6ApxX5/0iD+bKi1U=,tag:xNoL74kDhI1Fmu4HGAXC/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcUpOeVdGb2JZbjFZT2gx
            RVgya2lKQitaM0RoYnNQU1JtWlQxR3F1c3dFCmVnWlFTOE5SVTVKWnZSdlUrdDhN
            NVo5MzdMMUdlb0JRZEFBajgyem5QM3cKLS0tICtDQXNpc2U4eUJ2SENZNHB5WWYx
            UFlpVS9kU3lGVzJCT2w3M09POE8vK2MKy9hUP+R7LyguASYwszy7emzoETUfn3EG
            qdppIQNIF0r6We6khq2IMkRM1ubPKKoMUYXjLtNyfuteuV7YcsTbmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T01:35:29Z"
    mac: ENC[AES256_GCM,data:7CuKClWk42TxcCVHWn3tAUAqefEbAtF9eGp59WPwBlMWsQwwL37CavCnofq2bF3G+k1ZrvaHwwdIe5kacQmD+cx3p97+Df5FImQcuu+nnzYQH9GnpoqrBIC6UC4LTbD7se/vGNCK7P8lMLumbRy2/GCiEttCYNhneF0AQiHQIzs=,iv:G/3Ejb0aMMJgyybcLGLEdPLsRzYxnPL1acDBLogfWxM=,tag:OFSyTwoVlkP3s2tc3F9uZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
