apiVersion: v1
kind: Service
metadata:
  name: trading-solana-ingester
  namespace: customer1
  labels:
    app: trading-solana-ingester
spec:
  selector:
    app: trading-solana-ingester
  ports:
    - port: 80
      targetPort: 8002
      name: http
  type: ClusterIP
