apiVersion: v1
data:
  BOT_TOKEN: Nzk4NDkwNDI5NTpBQUUyaF8wZUp3cUVtV1hwcHdDWXdzXzZYQmtMZVdMY2dVQQ==
  CHAT_ID: NzUyODEzMDk0Nw==
kind: Secret
metadata:
  creationTimestamp: null
  name: alertbot
  namespace: customer1
