apiVersion: kustomize.config.k8s.io/v1beta1  
kind: Kustomization
namespace: customer1
resources:
  - ../../base/customer1/
  - ../../base/customer1/news_bot/
  - ../../base/customer1/openclaw/
  - ../../base/customer1/uncensored-bot/
  - ../../base/customer1/paaas-landing/
  - rbac.yaml 
