apiVersion: v1
kind: Service
metadata:
  name: trading-news-service
  namespace: customer1
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "trading-news-service"
    tailscale.com/tags: "tag:k8s-operator"
    tailscale.com/ports: "http:80"
spec:
  selector:
    app: trading-news-service
  ports:
    - port: 80
      targetPort: 8003
      name: http
  type: ClusterIP
