apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: hermes-health-check
  namespace: customer1
spec:
  default:
    config:
      type: TCP # Switched from HTTP to TCP
      tcpHealthCheck:
        port: 9118
