apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: hermes-health-check
  namespace: customer1
spec:
  targetRef:
    group: ""
    kind: Service
    name: http-tele-webhook
  default:
    config:
      type: TCP
      tcpHealthCheck:
        port: 9118
