apiVersion: apps/v1
kind: Deployment
metadata:
  name: paaas-landing
  namespace: customer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paaas-landing
  template:
    metadata:
      labels:
        app: paaas-landing
    spec:
      containers:
      - name: web
        image: ghcr.io/sirius0xdev/hermes_workspace:sha-7928dc9
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
        readinessProbe:
          httpGet:
            path: /          # or /index.html if needed
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: paaas-landing-svc
  namespace: customer1
  annotations:
    networking.gke.io/healthcheck-policy: paaas-healthcheck
spec:
  selector:
    app: paaas-landing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
