apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: paaas-healthcheck
  namespace: customer1
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    httpHealthCheck:
      port: 80
      requestPath: /
