apiVersion: v1
data:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:iJ5SoVIGSjdfXWZgV4iXK0WN7vaR/781X9FQbHy6R3ya6WZej2B+qXBCAlGwUOCxZxFGLuoUAbhi4sifk3JVNg==,iv:eev538DP17fSb7Xg5rCfnpnwQau8aiLkI5I9bpwpBOc=,tag:Jkuti5vmvCrnAMzJ4LX99A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: hermes-secrets
    namespace: customer1
sops:
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ODN5ZkdDTzVoM1BaTjNH
            Ty9DcitiZE9VYnBZRGN1Vk1HMzNDa0pydGhJClRpUU9ObFNvK3lYQUtWUmNzd0U2
            MGwvbzJVOGdQZ01ITlRqM041RitDMWsKLS0tIDI2N3MyaFZzRUJrMjB1bUFPb3NW
            QndZS2FlRFVCeHRBZ2pEeXBQMWNLclEKwzpXjr8A6mS0RuEQJmx+NThNhE7NH6hB
            mkTtsibO/kNki5Pcx8EjLQ+BHmLeJoUYtPJAJalErKMqaUt2BsaEfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T21:00:34Z"
    mac: ENC[AES256_GCM,data:cQ3tu7qEswvwwxklwuwfEpaDzspQNZkWqpg9aamIBMW2DaJ3gOM2d/N7lrnQjUvCWS6iYin+7VDNhNyYrSbh6ZOseK8Fr9cvfAxNOUpNd6hd951J2sCDORJxaxuqQPN3fuGG7JcKMHWuIKSAcWN5XnUb2Gn8Z1sW3k6U6pBvl88=,iv:3Ufa9NNRPJxLGfCISCsGIU6qDongpBHEcSQ/1l9oICg=,tag:2EKDkToBY3AHeG/e6HGMVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
