apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - new-deployment.yaml
  - hermes-secret.yaml
  - configmap.yaml
  - rays-hermes-secret.yaml
  - rays-deployment.yaml
  - api-server-configmap.yaml
  - hermes-webui-service.yaml
  - hermes-service.yaml
