---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: customer1
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "hermes-webui"
    tailscale.com/tags: "tag:k8s-operator"
    tailscale.com/https-only: "false"
spec:
  type: ClusterIP
  selector:
    app: open-webui
  ports:
    - port: 8080
      targetPort: 8080
      name: http
