---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: customer1
  annotations:
    tailscale.com/proxy: "true"
    tailscale.com/hostname: "hermes-webui"
spec:
  selector:
    app: open-webui
  ports:
    - port: 80
      targetPort: 8080
      name: http
