apiVersion: v1
data:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:PJeH0yhrNtHAm4FQCBKTqYkt4m9+maEM9lkXF4YTxV1S3gAr+NNcDQIc3KSsE//laxALZa5JYqhMgnHqsKq8aA==,iv:pjVF074inwQ17OnKgwzjcCK58prPcVz46PonzbGcq+M=,tag:s6weSORj/YHm2+VVEqQ2Lw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rays-hermes-secret
    namespace: customer1
sops:
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRzhtaXE1bDZ1RlJJdkho
            czdCS3NQWmZ3Mzh1Qm1kODBNSStkRkoxRWg0CjBGWm1DdUJqSUFjRDF0Z2w1c2NN
            OGh1S3FjYk54UDFHTXFIMmM3UytVRlEKLS0tIGVmN0xFNEZhbkJCMEh5OTE4VGc2
            L3FRWFdqYnlkUFl3amJFd094a2tRSEEKSMmIWPG2EJ2eJpqlCXJgq7DJofKM16VI
            B5KHxv8lRIAZe2UGSgs4+DkSV3bqB4mENA4yTVMYBVKtNka44OZLXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T22:47:13Z"
    mac: ENC[AES256_GCM,data:dC/CrMNN0wYIw5fNCh6uQjp8JaBJ91l1zM/WIts7jmtx4tRDPpJdca5ena2ISLKxmlet5IWXfAc1PgQ5jqGf6TseNVQi21znnGT0ag8g2QxkZx0xw+hz2QJIv49twbVAyigxIq+Zr2Hb3EkARqu2fN15t4jfS6CiYTpbOqQCq90=,iv:S06Xl0brsVkmRyzu5FDIHQo8Of9DD97oFw/mhR5Ogs8=,tag:3XJYh92ifaB60LVC05ud+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
