apiVersion: v1
data:
    TELEGRAM_WEBHOOK_SECRET: ENC[AES256_GCM,data:ONRrE7Zx5I/FGHrt/2gsSTVZy5k=,iv:77jEaIMDw+XmY3RPYF2Zf63nZxdcselLtrcG8V5F320=,tag:jl/wi2nnaNJDIM31nxESLQ==,type:str]
kind: Secret
metadata:
    name: telegram-webhook
    namespace: customer1
sops:
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR2J3T3JZOVpMT3lzNit4
            QUxuVUN4SFRwN0VXaEY4SlI0OCsvR042eHlnCkwvN2o2TENFaWZSMmFMSkVjdytu
            VFRTSkRSMU9sOU1tNm9vWU9YYmhod0EKLS0tIGd5T3BERjMxREpXdFluRHdIU0Rv
            dEtYS3pQQlY3eHhNNVdWMWZFeUs5ZFUKg0KEouv5XfOxmMMUUxOB1yHLhxRczXGO
            6bRY1NmmL0n1tUWRRldy4+aymnhUze9HqjUzHhLiUxzZ/rwiSNJz6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T15:37:21Z"
    mac: ENC[AES256_GCM,data:gkioesm0TgosWPHbm4nbHyo+Rnk4gXABvXoWD7ezJ7hs+9h/MBmu6ADFgFVn0BlSEU3ktMraggB4TacytAE55A7hdWjVRp27/f8EHPyngRCNkTq5GzGFC2EYAJe7L6Ep3iHx1gyzbHR9rJGxt311uY8muznm/bpQkfG/M0KeYmE=,iv:+11TYBwaab9wiWvoR8SDZ/PmwXt8cQhM8PmXO5qepe4=,tag:/AjgoakGeuMOnBxsbPJWYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
