apiVersion: ENC[AES256_GCM,data:RnI=,iv:8XkB3DGqi1C/kasS5GiQYudUFBMCA39P47f6ZrGXFfU=,tag:RbW4+ZJy23on1VHiVzB97A==,type:str]
kind: ENC[AES256_GCM,data:vQxp8Yye,iv:NTnSCRy/ojgI6YxiNQ5hGTyyc6oI/bBXellOT3zPHC4=,tag:DyarSVGeW4V/ZWpgIGSprg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cqxm72lY889Hep3e4gvIGczUbg6b07ztbDw=,iv:EdtJiYsDOr0JI03Q1ppcUeR6mAiWCAoGcDgoeSuBWJc=,tag:hbNuhZ/2ADJ8JbB04IDpyQ==,type:str]
    namespace: ENC[AES256_GCM,data:F5yrzxvlhG7r,iv:Bo6KQ5Jw//ujusHAKeFgbQZv9fiEjVGAcg2NfQoKkRQ=,tag:/7thf1cUYiXGpyJg+sB3sw==,type:str]
type: ENC[AES256_GCM,data:gub4U7je,iv:9+2u9x1CTCorIp4o0f9RkmQQxmFFZzzamIFT4lvv3k4=,tag:SfHYbfwTCRnS9BXggD/lNg==,type:str]
data:
    authkey: ENC[AES256_GCM,data:MECFadN0uzQGUvHeTrFEF3DU4HhkvksqSu1XXUs4whDhvlHduwCsCpHSQIRP4TkEFmPnufaKwc3/PKNi82/h2EzA0p8ZsTlB5MHBS1xyk+FLZn6X,iv:+kyMjGtN+Snh0Gs4sGe+UOHTLHtMGODDkjDCYUnLpeA=,tag:29vMCubpg3hlw18/26azzQ==,type:str]
sops:
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWFVseVR2ODNrUHJkUXp1
            eis0dmRhVTE1Z1lBME0vL3U1ektWQXBxY0JzClljNG9Tb0pHc2EzV2oySk1nd2Q0
            elgxdlpYK2JyOXR3SXdTSGJOR1ZHTUkKLS0tIEdDMUMzWDJ4VmZkN2Nxb1hCV1pS
            bTJCNEpKWDhFS1lPNFNhZVNIdnZQRHcKr+RoZ8Aci5qx31XLgARMnuMOe9rYJa74
            l0n1wSF6nO2u+TFEJ4CCSVZ8KiiZXgj1SI5RH0lB45RDX5TgiOsMVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T03:09:08Z"
    mac: ENC[AES256_GCM,data:XZUchEgndlDyUK9jUazTlBNqmtLe1NfSy2PR8MUsglcEfuGLopaORCsYBkINC5VfRiX7bxu9jEY7nlxwUNng8zHO6RVYo2c5l7ocbtbGafLcXmjUyVB1un2koMWZnk10PTKxq3+Tda1KztQ8+zvmdAZYsJFU8gyRuH5L5dK5B2o=,iv:uTOP9ByQIYUJXVdafgwE1XeR983QVHDjNDehVhYEEkk=,tag:HuV1QR6mav9SPE9eUQGrFA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
