apiVersion: ENC[AES256_GCM,data:NRg=,iv:wrgkO2zumRTaYoJc7d38N7KXS9hizgiCktfx2kZmyxU=,tag:oxNtxWk/WicjsJw5+51XNg==,type:str]
kind: ENC[AES256_GCM,data:ohOFcU5u,iv:8XyF9v76sLNYcDWy2UjzJtvdaKFRTiE0AMk2sRwOpJ0=,tag:phU5QersOFVTepljv4fGQg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oYmF2OCKGTLEc+5aFxS39K1+o2lIePVObhY=,iv:ioxTqEYNlDMYBnhcVrmHBQIWG3k4Cz5/U2LGaYJi3/4=,tag:REV5zmMtImFjybgzS5/25A==,type:str]
    namespace: ENC[AES256_GCM,data:kRVxhUT082MC,iv:AXgqD5uhs5VJIC8M8CkDE1gmfj3E1lCw3RhYjEXsWA8=,tag:ecKc+ET3JAQv5Rq5nquv0w==,type:str]
type: ENC[AES256_GCM,data:/DflUxxJ,iv:WIenl85o8aA8FwDEwXGJmUAzh0Mjdxes66MZLw15g3k=,tag:l1HZJWrXFUc86BNnBxm5MQ==,type:str]
stringData:
    authkey: ENC[AES256_GCM,data:VlCpY1j6y6Rcz22FFMO5BeBK80hvhPItZBm2SPZI7Q5p4eTUKoQlZHYc5Dq0/VcKju8aHtU5UXphi0OBLg==,iv:vJ1BlK8JvKqvgIUZdasZ/0Ufyc1K39kOMpT2ZIFk29A=,tag:IuTAzrokpVMlL0gCnCAVRg==,type:str]
sops:
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZUFlY0tDT0lxV1NHZlpq
            dWZWbkpLK3BVNk5qK2o3UFQrMVZnZjFLaHlNCmo0c3BKWk82QnZJYnVEdVRtWG9T
            SkNtRCt1NmN2L0tGRUlCUXljTkNES28KLS0tIGlFTUZpUXF6R0hRTmZVR2RIbUJj
            OGlPanpOOW4yeHRCUHpNSE1HT2V6UDgKgTybnkXVnkmutKCpzlnMDSjbGXLJQEM3
            Ipwj8jd8lKQG51/qFaHwwoMnHaVagFFKGsL8u4N2aiogag356qgwuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T00:43:53Z"
    mac: ENC[AES256_GCM,data:GkyA+glJn3u998iel1/HCxXRYEao7xf8NWYVSYwpaHvnVSAIG90aQhuT+hvPdzTVqd0PW3OIFu7658nBgRUvL3a68PS2rVPvJerzelnqrsMsqgBrDs7irZ+X2p+pio3NQgyCG6JQPFuuc4oFAFDo/NzNNxE/pGFn6zUkzMnfk1g=,iv:FTa1+YYYI2OHNFHZcqrY3gpQYxbX0mtxtLD7UM/TsgY=,tag:XtWrUWRUzbQjiEEAsyYurg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
