apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: monitoring-kube-prometheus-operator
  namespace: monitoring
spec:
  type: ingress
  hostnamePrefix: monitoring-kube-prometheus-operator
  serviceName: monitoring-kube-prometheus-operator
  tags:
    - tag:k8s-operator