apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: customer1

resources:
  - data-service
  - execute-service
  - news-service
  - solana-ingester
  - dashboard
  - configmaps
  - secrets
  - network-policies
  - routes
  - redis-cluster.yaml
