apiVersion: v1
kind: Secret
metadata:
    name: proxy-bot-secret
    namespace: customer1
type: Opaque
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:RSmlbm4p7786H1Fv53EtW+4Mqa5R6BjhD24Rh6Mn4UYipVxODmPtkh/pOoQ6FQ==,iv:85WV/8vZNKfqmwqWzRUhOXY0aToEnJmewCsjMf0JZUQ=,tag:2/KxDuyO1Eez1X5TWEnQKA==,type:str]
sops:
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTnF4OCtFaE42Vm5xb2lF
            UGFZWFlRZzVMY2xzdzBMaWFtY0JPZWxhUlVnCk81SGdTMWYvMHpWVnk4Yi81SHVa
            S2NUVmUrMlQ1VElMdXVsNkRFdkFEUTAKLS0tIExmRDVHdnJwemhLRjFBbkdzSlhP
            ckhhRWtTaFBsNWJTRVNiRmxLaHBpdWMKSObvzMAcgmKGetNlsK4SNVnrDBEzDehl
            LuaJC9ePnLiusaLxdAXE9cbhbGOpgfhKOKZz/CwR5vF5JpSehSY5oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T22:58:55Z"
    mac: ENC[AES256_GCM,data:QuaPZ3Rg2mkP410xdq332iDOHLqwip7Mbp6v7rcGAX9wwTL+W0+Km0gYR/aTNiuViu2E14OK79hAHZ567pdFcp2YprxCpgAwho0tYGcrgbvWHt0hBtBdzV+RVMa6p6FYD/f/aO/qytip3ORZxoLf8EQo0rGtIFpo7tNPPwO+r4I=,iv:70lVfBRfAkFhx2PokfHlRkcjLVRDge1OcJO76TDlhQY=,tag:ymynwmfed1oNX5rzkOlWOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
