apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  targetNamespace: cnpg-system
  interval: 30m 
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.26.1"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system 
      interval: 12h 
  install:
    createNamespace: true 

