apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnpg-backup-sa
  namespace: customer1  
  annotations:
    iam.gke.io/gcp-service-account: cnpg-backup-sa@devops-lab-cluster.iam.gserviceaccount.com

