apiVersion: v1
kind: Secret
metadata:
    name: execute-service-jwt-secret
    namespace: customer1
type: Opaque
stringData:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:XGO6xkUuVTtOod5+fJ2pFZixQZwxO3Ob20VwoTaJpBLphwoH4cUwuIVXEaqH7azFA9ffaDlvk+155659JKAbkg==,iv:EZiTKcPswqyM3WvKYTLlYBqXKxrI+GqG+a10SK7H3lM=,tag:38OLXoHUgj/3f+a5MO3akA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdjI0OElSMURaZVR0NHd6
            bThjQzhPUjdSZmg0YXZqUjVnM3JkQlV4cnpFCmdoQVBGVVBIdjUxTThXclR5RnBu
            QmJYb0xwM2FzRDlhdVM3NHpSc25mQ0EKLS0tIDE0R2JjTEEvMDlKWFFmdy9mSDVa
            b0JvTFZjaHRpZ3Y1MTdKRDlBQlNpTzgKER8m3SSQNpORgy8dAb6tAxlyQqoyviuX
            l749N8QN5U/RV2pqtsbfX7KKZNlAzXftp1Kpb1OpVuQApi7umAFCrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T01:52:12Z"
    mac: ENC[AES256_GCM,data:Zjvn6YPt+IQgQHgeBAqu9tB+lQM3yBo2ee8MT96lRcRlprdlbsRkugTjoshKO7yq6tkOK0o6k/iYBRx3QHnf3TDZ3KNkb11cyfsPPHBe1nHzzD1MCiQvZU/7TwLOwTPDC3hV+ceOnss3ACU2IkwqzVPROHM6zMSHvoa1XMvckBY=,iv:diaOY6qxOFL3h72H35NqW88rSf9Iii8cwhs46qDobXQ=,tag:TzrJLEYhJ98/ee1gMS3m4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
