apiVersion: v1
kind: Secret
metadata:
    name: solana-api-keys
    namespace: customer1
type: Opaque
stringData:
    helius-api-key: ENC[AES256_GCM,data:wuh0QeBFM7hNYxstHVy9usIKkY1KQein94ukEiPPI+6vtfZ2,iv:Jftq9HpvhjHEAqW/0h01i6qYr7g8baj3BbbGYrOq3hM=,tag:iOvqY6Ghde7Y3ur6FNR8LQ==,type:str]
    jupiter-api-key: ENC[AES256_GCM,data:nBQm47bEKb8jY8+IBgTAUK0pTUz8frZ+qw==,iv:OFr/6wuKvuXL7jvr2jdlJpWYaU8vciHn5fiIQ5vNCCI=,tag:kykbpOmUg91Miv3Rf/ufsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSVFNbC9kcEExbis3VFE1
            d2NPT3lCL2VQbnRnVlNNc3VTanBMZ3ZTbkVBCnNXUCtwUUlxcW94VGxkZ2ZYOTJQ
            YlFHelA1Zzl2U0RtRmtCaTFiWE9VNzQKLS0tIFI3T0g5d0dtWStSOFRobzlTeU1M
            bWdRTk9ib2dkMjU2eDZMZzRaTHFSUzQKRnlFkdQudt9iTKzoGvCAgumKSub9Twko
            cCc5JQcY4oFOR6huvdppGjsOt8X5jOX/PZrSh1cNikS1XkuD6MijEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T05:52:32Z"
    mac: ENC[AES256_GCM,data:PSb/+gby8U2JqIQBESGMz7/SKyvWTrc6ej3V5diLweWzsFofqlI0kN//VmYsB5Z+H19cTnnXVicZVXQtbNNv4I7Qgl1TCvuDzcgR37t6jPdv5iIlilCw8cFKw4gUB8c73L7bvHAKp0SI+nL1L6YJi5Wn5f2CTxpFE5RD5HL14pA=,iv:aVjd9KUvcfFYKO11i9jIJUVbllxeul84xjowBej1B3g=,tag:KKRTlWsyzoHs7+dLs/oMdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
