apiVersion: v1
kind: Secret
metadata:
    name: solana-api-keys
    namespace: customer1
type: Opaque
stringData:
    helius-api-key: ENC[AES256_GCM,data:72/f2NS9yBS2125QpiTxGBz6K8m7iHx9,iv:0xQ4xCKji6NNWJUfuiiEvb8IoTJxXGhmoZJo2MDVaKw=,tag:m8JAjswKIjsGjeNU0G4zNw==,type:str]
    jupiter-api-key: ENC[AES256_GCM,data:nBQm47bEKb8jY8+IBgTAUK0pTUz8frZ+qw==,iv:OFr/6wuKvuXL7jvr2jdlJpWYaU8vciHn5fiIQ5vNCCI=,tag:kykbpOmUg91Miv3Rf/ufsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSVFNbC9kcEExbis3VFE1
            d2NPT3lCL2VQbnRnVlNNc3VTanBMZ3ZTbkVBCnNXUCtwUUlxcW94VGxkZ2ZYOTJQ
            YlFHelA1Zzl2U0RtRmtCaTFiWE9VNzQKLS0tIFI3T0g5d0dtWStSOFRobzlTeU1M
            bWdRTk9ib2dkMjU2eDZMZzRaTHFSUzQKRnlFkdQudt9iTKzoGvCAgumKSub9Twko
            cCc5JQcY4oFOR6huvdppGjsOt8X5jOX/PZrSh1cNikS1XkuD6MijEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T04:35:33Z"
    mac: ENC[AES256_GCM,data:N+uI8Fr3ydaGM6pdZRC8ML7BlnEjoYj4Wr+cYCL613OPCzK4H6uZB94gf6MNW4IBuAA3qV3Ug6Ynj/edZCYUTdCTx/Ol5qii26DhPrRMzgn0ipvGZ33OhAO+YCbNa0Wy7PZytn+Lchu5klvbqXp7QSXt+UjKvYZLXIdy13Iw8So=,iv:Nt8uA1zRN5N0njgisVJ0q6tWNYmx/tTobQ2c9M/CCp4=,tag:0Uo7g7AHUzPGvKc8HgsIZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
