apiVersion: v1
kind: Secret
metadata:
    name: trading-platform-secrets
    namespace: customer1
type: Opaque
stringData:
    #ENC[AES256_GCM,data:dyXLfea8iq2yHlZep1eNdTLJ32FJ1njYaZFgwHTGSSpGpBu+mg==,iv:Ag6MtzvQH71KIBO0EXYDXYIlzi9Tkrzbv5yAnGeTWzI=,tag:5CbRxFAJhz3ygqHkYfQ3aA==,type:comment]
    news-api-key: ENC[AES256_GCM,data:oPEYLf8a8qGHcOqpJf4nNEJ0thnC92je,iv:L5h71TK3+bCzEfG+mWJWtAJElUAYax8j1wufPRJwz98=,tag:jhcLILef6NI0NaHYnVIDcA==,type:str]
    market-data-api-key: ENC[AES256_GCM,data:dIiQPEBaBVNrxSu15WL3+eq56NKmhjxN9VfIBeXyqw==,iv:QTzb0Ivyg1pZxp5lEW+Qf1+If8M8Qof2BfSwZq/O8AU=,tag:K5Do7SXs0gpaJPqakntoSg==,type:str]
    #ENC[AES256_GCM,data:yimW2HNmOjOVEBNcfLZNl+TDx+mmTd7c,iv:wb5QUD9X3+m/phr4x/TGqnTG02Fl1jqJuPdp0YW9Jcw=,tag:fXpKSc0X3ZyMBGwEvUBnMw==,type:comment]
    service-auth-token: ENC[AES256_GCM,data:JunmMQGPSWD0PRVN4PbGcCKaTTeZfl5US3LsS12L,iv:+qJjWstEiqarjVArzIcu1fUpp8ySXMf84pHepyK4XWI=,tag:hb+CSxl8j4zwxFrqn1TlPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Mmt5alJSa1Z4dWF3anpU
            RktDZTdQcExCeTV4THcwWUFDbmlKaWxqTGp3CmNIQVlmMENNem9leHJZdGJNbys0
            RG1aR0w4aExtYStXU0YwRmVoRDhib0UKLS0tIHBGK0phRXpGNXF4OVM5TTlxcnRE
            VXY5R3M4aVp2RnRqS25abThBdWJxZUUKRh/BANhV9to++utXiIVnh7KavNfwwhTs
            rSyLXlRVHAUMghQTPB91RAk7QmozpRUWLlf09TZVRtdyNTwlCzSwYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T04:35:21Z"
    mac: ENC[AES256_GCM,data:ClIlomZn/x9hILztsNtlxKb4sIYHDTL0gXJ6d7Yed7BUrIy5sUZCzaE4cB40sq3hxS2p3XCNQ4wr2hzEl549r4zUn0gC69U/lJcSQkIzI6qD4DlksCweFLmsPbU9XiActkmw9MKFRN6GVufCepCXnWqZOKGAps8br3wWConqv8w=,iv:KpldaQ4K6LMmLr1WpZci96VzYACMZwuKopomHXr7EsM=,tag:BL2Fl0le7axNYwa/F5odJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
