apiVersion: v1
kind: Service
metadata:
  name: embedding-service
  namespace: customer1
  labels:
    app: embedding-service
spec:
  type: ClusterIP
  selector:
    app: embedding-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
