apiVersion: v1
kind: Secret
metadata:
    name: hermes-db-credentials
    namespace: customer1
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:4QolDU9x,iv:hDtGbpDnzwEMTFsb0AN4Mj0DYJ7gJJGVtG87RZYyBT4=,tag:Po0IES1AfnIoq3Bl2TWnsA==,type:str]
    password: ENC[AES256_GCM,data:0uMXswkEF/RlH5PLFfOrew7/n9URpf5YM7GMnoEVO0k=,iv:9LasAdfoBbTeEXCQmFjGjNnB5UY4JxX4QM7V4YY0GiU=,tag:L3Kb9Z366jdBe3p1a3hdzQ==,type:str]
sops:
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWXhlYmxJMnd6THgrbE5Z
            Si9wWkI2bklvTWZSR1lodWpVTTIwV3dNODFnCnhKRSsveFRMbFBvZGMrM00wd2hy
            UTBHQTZERUhGWmt0aVdlWmZDYVNOWjAKLS0tIGI3Z0lFTHN3ZUhYNUxrdzVEb09n
            dDFrSzZTdDU0NVU2YUNCK0NqdTdhQUkKL1Pp3OY0S/u1f1KxcXqgtdQ8V466W0On
            Lw0FLig3aeAQG+XTGLbC8WYYxPYLznk5vKJlCZPK1A4O42zixiLOSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T22:14:04Z"
    mac: ENC[AES256_GCM,data:kkIkkVXXUvEvnky8EIqWdOGw10pAShuwJ/B1g0HW49iUchP8sEDJbP2o7NFQKVcj14Rpo7FfpiIcO12yh/WngAUo2o0kXYQsJNnMqpnePyHePwWWcTaiXE/8pqLuL0bTQ3MWK/Xp5CH/tvf22rS9ntuNTBDmhGqQDm+qqNyw/sA=,iv:yYxAfWg/b4WtdnP78AJDwxRWAonvSVPRtxqQrlytIwA=,tag:bNFwg3cxD+ZrZGQT8coePA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
