apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pg-cluster-hermes.yaml
  - hermes-db-credentials.yaml
  - memory-db-credentials.yaml
  - agent-memory-db.yaml
  - agent-memory-rag-db.yaml
  - hermes-scheduled-backup.yaml
  - kafka-broker.yaml
  - redis-cluster.yaml
  - rag-init-sql-configmap.yaml
  - rag-init-job.yaml
