apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #- pg-cluster-hermes.yaml
  - hermes-db-credentials.yaml
  #- trading-db-credentials.yaml
  #- memory-db-credentials.yaml
  #- trading-data-db.yaml
  #- agent-memory-db.yaml
 # - hermes-scheduled-backup.yaml
