apiVersion: v1
kind: Secret
metadata:
    name: memory-db-credentials
    namespace: customer1
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:aBZzGnqc,iv:V27qpmj00bYIERMxBGZ72bHkN6rIkdrSOzzDRj21kpA=,tag:7mCcAeOe+Gst2Fw6dZt2dw==,type:str]
    password: ENC[AES256_GCM,data:B02Xw4UUoGvjLFd2AYYx6kVHeQ2q+K40NHgNguna5BU=,iv:+Cli7nB2j5DC6zI0uXfFYUkBsz2XRMwm3y81WsuRzCA=,tag:ziIEeiW+rkkkAkDnWmCb7Q==,type:str]
sops:
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZ09BMHFWRGNJMGJpdGpL
            ZGZGL0tvWWUwVXRWNlBpUU9QUHZEcUF5emdrCkh5RmFTeWpMY2UyalVwZFNLVXhk
            MW4rS202MktiekxKZzZBbnpwVlowRXcKLS0tIDlpK2VycDRxMHdPeExycmNMZXh6
            YTVBaVFobTZieStEN3pUVy9ZVU5iKzAKxozE9s5lFIuvnh/R0ySDkLoYQ8lV62KT
            hVkeBYdK5u9gGakmw+okUVNKS2Hh+7Mio6OIvM+jLrpTgsd8NzabWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T22:14:04Z"
    mac: ENC[AES256_GCM,data:yKiV+s5d5O/XT+J92ShQR0rqnSc+VnmH3BnvfNdkOqfMjZsYQAWLtEmGaOKUCCkWwvE1J4B5DhmMAuPhb5RVekirZkQyaXqPO7MA2riRvFQD24MZGtAeGHRRiLMH4L/UMEAm3YqtSKOj5tfjWica4pXQDsmLS0b/qNq+kXTo/aI=,iv:YuG+qxuwYOflVzW+hj8frwhpD833+xAMx6aki0dG8Qw=,tag:ExMYr24Xqztp8atid2eCBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
