apiVersion: v1
kind: Secret
metadata:
    name: trading-db-credentials
    namespace: customer1
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:M3gBIiP+uA==,iv:QhosCv8SfKcGMzy0Ja9+son5okXVtML5l9JUi/c2C9U=,tag:juYKzLFLsDGXSsgaF/BI3g==,type:str]
    password: ENC[AES256_GCM,data:9ajk/hBlnzkg2fi/zM0Rzx9MACyMKhtyv3lOERBcR4Y=,iv:voTjlgJVgO8yXirIgbAzg8MqmSxAdmmPPtPpeWYLqwA=,tag:RBBl4xD0NplMqp8y6oS8uw==,type:str]
sops:
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZDg2amk0eVZSRUUvNkdO
            TTIySjB3QVpwMjlIcWE1dDBEeVBUSDlLbGpNCmVIL3hGeWY4TDJORGk0amZNU1dC
            czdwRFM3c2VTcVZUVXZoUUM0R0JNY2MKLS0tIHI3ODhRMjJ6NHhDSjBEbGx4QURj
            eVI0d1ZhNStZajU5K2lEVmhNalRrWDgKJStJ5MsUWBF1Ceq1uiTwxu8R8dzFz+SL
            MtFisTEwxgu5HoMpj3hxiDIMWi2pflp/iDwksK43BSw9lTHNYyQDWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T22:14:04Z"
    mac: ENC[AES256_GCM,data:Tkg6KYjxddWMynrLZP26zjP+fp++WtMaPDf79CJie/Kps6PvFWHXDAXAhcS406xOEdj29IgBjrCGJp9PQK7nmI9UXw//p+s201jhG+hFCCG+estOmZyFJL0sHDZlAWx/993swwymDfTX564AfC7dj61MqdCQUz3BISSCjK4Tyd8=,iv:nC9LetZDlQ8SCiFf0MYi7og6qy76+tz7+7v6UM3PJrg=,tag:cWhU1egQAtVYwSZ9vbRi4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
