apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: rtx6000-scaling
  namespace: customer1
spec:
  hosts:
  - rtx6000-brain-service.customer1.svc.cluster.local
  scaleTargetRef:
    name: rtx6000-brain-vllm
    kind: Deployment
    apiVersion: apps/v1
    service: rtx6000-brain-service
    port: 8000
  replicas:
    min: 1
    max: 1
 
