apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-data-service-config
  namespace: customer1
data:
  DB_HOST: "siriusdevops-pgdb-rw.customer1.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "trading_data"
  REDIS_HOST: "trading-redis.customer1.svc.cluster.local"
  REDIS_PORT: "6379"
  KAFKA_BROKER: "trading-kafka-kafka-bootstrap.customer1.svc.cluster.local:9092"
  KAFKA_BOOTSTRAP_SERVERS: "trading-kafka-kafka-bootstrap.customer1.svc.cluster.local:9092"
  KAFKA_GROUP_ID: "data-service-consumer"
  KAFKA_AUTO_OFFSET_RESET: "latest"
  HELIUS_RPC_ENDPOINT: "https://mainnet.helius-rpc.com"
  JUPITER_API_URL: "https://quote-api.jup.ag/v6"
  LOG_LEVEL: "info"
