apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-execute-service-config
  namespace: customer1
data:
  EXECUTE_DB_HOST: "siriusdevops-pgdb-rw.customer1.svc.cluster.local"
  EXECUTE_DB_PORT: "5432"
  EXECUTE_DB_NAME: "trading_data"
  EXECUTE_REDIS_HOST: "trading-redis.customer1.svc.cluster.local"
  EXECUTE_REDIS_PORT: "6379"
  EXECUTE_KAFKA_BOOTSTRAP_SERVERS: "trading-kafka.customer1.svc.cluster.local:9092"
  EXECUTE_LOG_LEVEL: "info"
