apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-solana-ingester-config
  namespace: customer1
data:
  HELIUS_RPC_ENDPOINT: "https://mainnet.helius-rpc.com"
  JUPITER_API_URL: "https://quote-api.jup.ag/v6"
  KAFKA_BROKER: "trading-kafka.customer1.svc.cluster.local:9092"
  KAFKA_TOPIC: "solana-market-data"
  LOG_LEVEL: "info"
