apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pg-cluster-siriusdevops.yaml
  - waitlist-db-credentials.yaml
  - waitlist-db.yaml
  - siriusdevops-scheduled-backup.yaml
  # New trading dashboard DB
  - trading-dashboard-db-credentials.yaml
 
 #- trading-dashboard-db.yaml
