apiVersion: batch/v1
kind: CronJob
metadata:
  name: analyst-gemma
  namespace: customer1 
spec:
  schedule: "15 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: analyst
              image: siriussec/summarizerlocal:3.5
              imagePullPolicy: Always
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: news-app-password
                      key: password
              envFrom:
                - configMapRef:
                    name: gemma-config 

          restartPolicy: OnFailure

