apiVersion: v1
kind: ConfigMap
metadata:
  name: gemma-config
  namespace: customer1 
data:
  DB_HOST: "customer1-pgdb-rw"
  DB_NAME: "news_app_db"
  DB_USER: "news_app"
  DB_PORT: "5432"
  LLM_URL: "http://localhost:11434" 
  MODEL_NAME: "qwen2.5:14b-instruct"
  SUMMARY_PROMPT: |
      You are an expert news analyst working for Sirius Media. Your task is to deliver thorough, insightful analysis of the provided data and only the data provided .
      Only the provided data is to be analyzed 
      For reference the current year is 2026.
      DATA:
      
      {final_input}

      Instructions:
      - DO NOT USE ANY OF YOUR PRIOR TRAINING DATA. ONLY report back on the data given.
      - Make telegram friendly with some emojis and formating 
      - Identify the 3–6 most impactful events or developments.
      - For each impactful event: Write a detailed 4–6 sentence summary, including key facts, context, potential consequences, and why it matters strategically.
      - Also give 5-6 local news events that stand out . Give 3-4 sentence summary of those
      - Aim for a total output length of 800–1200 words. Be comprehensive but concise.
      - Use neutral, professional, analytical tone with precise language.
      - Do not inject any stories Only report back on the provided data.
      - At the end give 3-6 stock tickers of companies that may bennefit or fall from the articles .
      - Structure your response clearly and telegram friendly
      - Output ONLY the structured report translate everything to English — no introductions, apologies, or meta-comments like "no major events found".
