apiVersion: v1
data:
    password: ENC[AES256_GCM,data:d2MAWwaRAWBsz+/VNV46whVTqBY=,iv:B7Ho0E6Xkj9jQvUBM0EfwoMzdBKaS4l85KXkyO52xgM=,tag:WpdaN5bW9FQjpyMChTAR7w==,type:str]
    username: ENC[AES256_GCM,data:ZofCHAydBukvd0NK,iv:QkEbrjtD1NTCZdVDbFZsKzC6rh4paPSSc/jRupOnl5s=,tag:T/aeQY13Gi5hOs9l8eXaIg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: news-app-password
    namespace: customer1
sops:
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMTd4bnRsdnRQeXJ0RXBv
            a3I1RmVheWx4S3dCVzI2Z0tDRnI0U0EzUFVFCnlOaUpGOHNTYUtHZ1g2MmpRT1M3
            YXJBUGFxWGNDUHlONFhpckt5QXV5MEUKLS0tIDdKeEpTSGdwQXZrUzRFWlQxZWtx
            UEVZZzJRWjlmWFpLUUZnSVhxZWRsZUkKeEM9QZTc2dxD6JWJveid8yz9lBeTMsWy
            3omHFX2Ej5XAcM9RemiGHwclp2UBL8++5JeJlnVTbvNn+IkeH3gu5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T19:23:13Z"
    mac: ENC[AES256_GCM,data:1Ddf5/F620muz4gDcGRaSAGFD4zKFyVEvc3uqPppG8NMdwMXhOrTMmkb2TXkpMcqdnt/sbX5hD9me+FHZ0yvttlf27uc/bI+RRoJDo9b3MJd6OkBB9YPTtPZ7WJXmBcfejPAHo8RSoM3Q9Y8EjbTxUBNfi7qLdMK/l3rW9lonhg=,iv:qQU5EhgkSuAdV0Rd9nr/c0wJhWgFK9IWSetLwfmA9Xs=,tag:7wSkcR8j6dBz+6WqSwIAWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
