apiVersion: batch/v1
kind: CronJob
metadata:
  name: deepseek-analyst-v1.2 
  namespace: customer1 
spec:
  schedule: "15 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: analyst
              image: ghcr.io/sirius0xdev/news-analyst:latest
              imagePullPolicy: Always
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: news-app-password
                      key: password
              envFrom:
                - configMapRef:
                    name: deepseek-config 
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
          restartPolicy: OnFailure
