
apiVersion: batch/v1
kind: CronJob 
metadata:
  name: news-scraper
  namespace: customer1
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec: 
          containers:
          - name: news-scraper
            image: siriussec/newsscraper:0.5.1
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            envFrom:
            - configMapRef:
                name: scrapy-config
            env:
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: news-user-password 
                    key: password 
            volumeMounts:
              - name: url-storage
                mountPath: /app/urls.txt
                subPath: urls.txt
              
              - mountPath: /dev/shm
                name: dshm 
          volumes:
            - name: url-storage
              configMap:
                name: scrapy-urls 
            - name: dshm
              emptyDir:
                medium: Memory 
          restartPolicy: OnFailure       
          
