apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: openclaw-brain-a100-scaling
  namespace: customer1
spec:
  scaleTargetRef:
    name: openclaw-brain-vllm
    kind: Deployment
    apiVersion: apps/v1
  hosts:
    - openclaw-brain-service.customer1.svc.cluster.local
  replicas:
    min: 0
    max: 1
  targetPendingRequests: 1
  scaledownPeriod: 3600
