apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - a100-vllm.yaml
  - keda-a100.yaml
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - openclaw-secrets.yaml
  - pg-cluster-openclaw.yaml
 # - vllm-l4.yaml
 # - vllm-gemma.yaml
