apiVersion: v1
data:
  GEMINI_API_KEY: QVEuQWI4Uk42TGNDQjRsY21SYmRkVXZGb2EzTDBQMEpWY2R4VmZHVEt2Wmc0OG9fZE9QaVE=
  OPENCLAW_GATEWAY_TOKEN: YzRmOGU0ZWM1MzQ1M2FlMjVjMTJkOWY5OTU3MjQ1Y2Y0OTkzODIyNzEwZjUxNzA1M2Y5M2IzMzg1MGRlNjNkNg==
  TELEGRAM_BOT_TOKEN: ODY0NTkxNTgzODpBQUd4NVZyOWkxZWRhR3p3TUtiY1VLbFZfN1pjT3hVeHZndw==
kind: Secret
metadata:
  creationTimestamp: null
  name: openclaw-secrets
  namespace: customer1
