apiVersion: v1
data:
    GEMINI_API_KEY: ENC[AES256_GCM,data:uAwqMc6chYD8BeOOhxExHzdPClFHy3A2346f7Yt43XvebH0t/qC5gZWFC5GWvOWT6BI8l9szsMGWC1SADYlb5QnW5iCI9stQ,iv:WSCMH0UtamnUrarSd9mGGoFbqc7M6cBzecAJvK9UvAk=,tag:2kZ14+1qDsyYDk5JoCQEPQ==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:hRfU3vGUFsQ1pLo+IJM/QjNZdgExbew/xGBQEidP3uMFfpfmaYPBYGNM5NmRYLR7RYy98Co+DKU/EK2IuMMVsyxidkPEIyNuVPjirWXADxpnr7qvGgoi7w==,iv:4ofuXyr4iFC0I/u1kk5WxZ58PHzbU/jkPvcFwBApmH4=,tag:RlDqbTIhf0+J7CnIWH86Zw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: openclaw-secrets
    namespace: customer1
sops:
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cDJXYjdTR0xteEtRRUZT
            YXZnQitKNWZoRGZRL0ZwV1VLZDBLQ3R3bDBVCkNoalRTaWV0OWgvcUZBWHZBYk5i
            M2VoQ0dFRlJzYmYzY283allLU3N5YVEKLS0tIHhwQit0WFNHMlY0VWJSOW12bE1Z
            SHZoc2lkZEdYVUp1ZWJEYVF4STRzOGcKZUCxyHMFR7PYhrx7I/Owy6KXbn7WeLML
            9V+fJCIuCJzMbnYGrs0rIgVxs7PhDNjmWEJ0HugJ/aGq1P+8AJrxVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T03:19:43Z"
    mac: ENC[AES256_GCM,data:OMMlcv+BnwlpbyK3NsspYp8GpSFTxCpH/WRSNaJ1vaGvTV+LPECto6Vhfl/gfw0MZkY50lcIKb2XZ+vfSfptgTaB/70J6gVxh+elrMnCbozA0HPoSsU1TzqdK3UuupoNjboaIUcVfx3HV+ttT4BEwjnk7mNSSwwDAvV5GF4vxlI=,iv:FNBEFc7XP9b5NhMl9qHSBLtxs5zyqlB/by6YMCQZl7g=,tag:HJXHL876qR4OwDEc8O2meA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
