apiVersion: v1
data:
    GEMINI_API_KEY: ENC[AES256_GCM,data:RZA/F1BEe+/xyh6TxosWjwAmSIg1eUZHkt0jyYTUloYAXOOQ3fy4eiUEpIJ7NZsq+HPuvanYp02918AhJNxlZj3xXGma/zWE,iv:LntCrdxnRbCSe116WCSmcBeg+KGeC2ssYcYt6IdBZMA=,tag:dFDR2TVZTgD9VjgcEboQ+w==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:ssT9kEGYZpwf9mIxT4LPHN9QedMGYmjgBiiNfh9NmJ9WgfRgsglh/L54JROHtkLNeaCFzY6TayDSICd8KaPCofPK8wY6W+3QHXXSFcOXdymhkBXaFsKedQ==,iv:n2jP04eOL1owky8rhXzrqqmxx6s1ozB37NZQ5pB0pu0=,tag:HK9yuBxUNsPPX6wm3pNknw==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:8OGyPU/Ic+qJpy4KwlGoUq6g5g1YOgAf8cYKc58Yne866te4tY3Am6iDksfW0sw+foh5hgUAXZhhGlRptcFM+A==,iv:acxCfNxkSg38Fy/6GUKIXtz1/Ocj7Y45ce7BNeX+SmI=,tag:DiquEVrc7wm8AbETYI4vVw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: openclaw-secrets
    namespace: customer1
sops:
    age:
        - recipient: age1uuxf066xuuqgvjppxfcmqkwfcufnwp3wcwnl9h20g9k4l8nkw9jsaungf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaVZjTStvZFFabFJLT2FF
            TjJqd2oyOHRnQWlISXNBR0EyQ28ycTR1TFg4CnBqeGFqQi9HL004TFoxbkVLRTZ1
            TWtlOEFtb0drWHVXUFVFdVZSclFUSlUKLS0tICtCYk40WkdBdVQ0dFJ0VDVGTUJj
            SUNVeEZGL1NZSVdKUHdpYUxmRUVtSkkKZDnqcW8SHmuvmW2mBbhXKVTubsJBNZ3+
            qEF+5tsi55YrEzyExig2ALFlSzfprNPi9trAhDR6hiUTmlwfVoIQ/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T23:00:23Z"
    mac: ENC[AES256_GCM,data:ghjMTX95Cex3m5upIQfQCK7FqnnXujwhMYJWnhurQg1qR977d9jdEJ+0xSGLZnfazEDkTJnZ3RAWA/axHHd8elVFFtwF1XYBCP5MSf3rQ47pEBg2544ythwlUqBY8BB4jK2lb89eDhzHMWd9x4pYmyDuMKUQl8wOjfaJF71S9l8=,iv:RBroeuHQ/wjr/XOSE+tE4lNqOd3TZt90TL2Cgq59HSM=,tag:FDSaaElIrVVzpvGZbqae6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
